In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

df=pd.read_csv('hospital_er_data.csv')
df.head(10)

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patients CM
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,NaN,False,10.0,39,0
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,0
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,General Practice,True,9.0,55,0
3,358-31-9711,04-02-2024 22:34,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,0
4,289-26-0537,04-09-2024 17:48,Y,Gionettitti,M,5,African American,Orthopedics,False,NaN,10,0
5,255-51-2877,20-04-2023 00:13,H,Buff,M,58,Asian,NaN,False,NaN,59,0
6,465-97-0990,23-08-2023 08:26,F,Perrat,F,68,White,NaN,True,NaN,43,0
7,157-31-7520,29-07-2023 16:57,K,Gwillim,F,47,Two or More Races,NaN,True,NaN,23,0
8,432-34-5614,19-02-2024 06:54,E,Dewhirst,F,79,White,NaN,False,1.0,42,0
9,609-17-8678,11-10-2024 05:25,M,Crebo,M,62,African American,NaN,False,NaN,51,0

In [3]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ','_')
)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   patient_id                  9216 non-null   str
 1   patient_admission_date      9216 non-null   str
 2   patient_first_inital        9216 non-null   str
 3   patient_last_name           9216 non-null   str
 4   patient_gender              9216 non-null   str
 5   patient_age                 9216 non-null   int64
 6   patient_race                9216 non-null   str
 7   department_referral         3816 non-null   str
 8   patient_admission_flag      9216 non-null   bool
 9   patient_satisfaction_score  2517 non-null   float64
 10  patient_waittime            9216 non-null   int64
 11  patients_cm                 9216 non-null   int64
dtypes: bool(1), float64(1), int64(3), str(7)
memory usage: 801.1 KB

In [4]:
df['patient_admission_date']=pd.to_datetime(df['patient_admission_date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   patient_id                  9216 non-null   str
 1   patient_admission_date      9216 non-null   datetime64[us]
 2   patient_first_inital        9216 non-null   str
 3   patient_last_name           9216 non-null   str
 4   patient_gender              9216 non-null   str
 5   patient_age                 9216 non-null   int64
 6   patient_race                9216 non-null   str
 7   department_referral         3816 non-null   str
 8   patient_admission_flag      9216 non-null   bool
 9   patient_satisfaction_score  2517 non-null   float64
 10  patient_waittime            9216 non-null   int64
 11  patients_cm                 9216 non-null   int64
dtypes: bool(1), datetime64[us](1), float64(1), int64(3), str(6)
memory usage: 801.1 KB

C:\Users\KIIT\AppData\Local\Temp\ipykernel_13192\4092818416.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['patient_admission_date']=pd.to_datetime(df['patient_admission_date'])

In [8]:
df['patient_name']=df['patient_first_inital'] + ' ' + df['patient_last_name']
df.head(10)

,patient_id,patient_admission_date,patient_first_inital,patient_last_name,patient_gender,patient_age,patient_race,department_referral,patient_admission_flag,patient_satisfaction_score,patient_waittime,patients_cm,patient_name
0,145-39-5406,2024-03-20 08:47:00,H,Glasspool,M,69,White,NaN,False,10.0,39,0,H Glasspool
1,316-34-3057,2024-06-15 11:29:00,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,0,X Methuen
2,897-46-3852,2024-06-20 09:13:00,P,Schubuser,F,56,African American,General Practice,True,9.0,55,0,P Schubuser
3,358-31-9711,2024-02-04 22:34:00,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,0,U Titcombe
4,289-26-0537,2024-09-04 17:48:00,Y,Gionettitti,M,5,African American,Orthopedics,False,NaN,10,0,Y Gionettitti
5,255-51-2877,2023-04-20 00:13:00,H,Buff,M,58,Asian,NaN,False,NaN,59,0,H Buff
6,465-97-0990,2023-08-23 08:26:00,F,Perrat,F,68,White,NaN,True,NaN,43,0,F Perrat
7,157-31-7520,2023-07-29 16:57:00,K,Gwillim,F,47,Two or More Races,NaN,True,NaN,23,0,K Gwillim
8,432-34-5614,2024-02-19 06:54:00,E,Dewhirst,F,79,White,NaN,False,1.0,42,0,E Dewhirst
9,609-17-8678,2024-10-11 05:25:00,M,Crebo,M,62,African American,NaN,False,NaN,51,0,M Crebo

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
for col in ['patient_gender', 'patient_race', 'department_referral', 'patient_admission_flag']:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- patient_gender ---
patient_gender
M     4705
F     4487
NC      24
Name: count, dtype: int64

--- patient_race ---
patient_race
White                            2571
African American                 1951
Two or More Races                1557
Asian                            1060
Declined to Identify             1030
Pacific Islander                  549
Native American/Alaska Native     498
Name: count, dtype: int64

--- department_referral ---
department_referral
NaN                 5400
General Practice    1840
Orthopedics          995
Physiotherapy        276
Cardiology           248
Neurology            193
Gastroenterology     178
Renal                 86
Name: count, dtype: int64

--- patient_admission_flag ---
patient_admission_flag
True     4612
False    4604
Name: count, dtype: int64

In [11]:
df.isnull().sum()

patient_id                       0
patient_admission_date           0
patient_first_inital             0
patient_last_name                0
patient_gender                   0
patient_age                      0
patient_race                     0
department_referral           5400
patient_admission_flag           0
patient_satisfaction_score    6699
patient_waittime                 0
patients_cm                      0
patient_name                     0
dtype: int64

In [12]:
df[df['department_referral'].isna()][
    ['patient_admission_flag', 'patient_satisfaction_score', 'patient_waittime']
].head(20)

    patient_admission_flag  patient_satisfaction_score  patient_waittime
0                    False                        10.0                39
1                     True                         NaN                27
5                    False                         NaN                59
6                     True                         NaN                43
7                     True                         NaN                23
8                    False                         1.0                42
9                    False                         NaN                51
13                   False                         NaN                45
14                    True                         NaN                49
15                    True                         NaN                57
17                   False                         NaN                55
19                    True                         2.0                40
20                    True                         NaN                25
21                   False                         2.0                51
22                   False                         4.0                30
24                    True                         NaN                23
25                   False                         0.0                51
26                   False                         NaN                58
29                    True                         NaN                37
32                   False                         NaN                53

In [13]:
df.groupby('patient_admission_flag')['patient_satisfaction_score'].agg(
    ['count', 'mean', 'min', 'max']
)

                        count      mean  min   max
patient_admission_flag
False                    1282  4.910296  0.0  10.0
True                     1235  5.076923  0.0  10.0

In [14]:
df.groupby('patient_admission_flag')['department_referral'].apply(
    lambda x: x.notna().sum()
)

patient_admission_flag
False    1940
True     1876
Name: department_referral, dtype: int64

In [15]:
df[['patient_age',
    'patient_waittime',
    'patient_satisfaction_score',
    'patients_cm']].describe()

       patient_age  patient_waittime  patient_satisfaction_score  patients_cm
count  9216.000000       9216.000000                 2517.000000  9216.000000
mean     39.855143         35.259874                    4.992054     0.052083
std      22.755125         14.735323                    3.138043     0.222207
min       1.000000         10.000000                    0.000000     0.000000
25%      20.000000         23.000000                    2.000000     0.000000
50%      39.000000         35.000000                    5.000000     0.000000
75%      60.000000         48.000000                    8.000000     0.000000
max      79.000000         60.000000                   10.000000     1.000000

In [16]:
df.dtypes

patient_id                               str
patient_admission_date        datetime64[us]
patient_first_inital                     str
patient_last_name                        str
patient_gender                           str
patient_age                            int64
patient_race                             str
department_referral                      str
patient_admission_flag                  bool
patient_satisfaction_score           float64
patient_waittime                       int64
patients_cm                            int64
patient_name                             str
dtype: object

In [ ]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("password")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/healthcare"
)

In [18]:
df.to_sql(
    'hospital_er',
    engine,
    if_exists='replace',
    index=False
)

216

In [19]:
pd.read_sql("SELECT * FROM hospital_er LIMIT 5;", engine)

,patient_id,patient_admission_date,patient_first_inital,patient_last_name,patient_gender,patient_age,patient_race,department_referral,patient_admission_flag,patient_satisfaction_score,patient_waittime,patients_cm,patient_name
0,145-39-5406,2024-03-20 08:47:00,H,Glasspool,M,69,White,NaN,False,10.0,39,0,H Glasspool
1,316-34-3057,2024-06-15 11:29:00,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,0,X Methuen
2,897-46-3852,2024-06-20 09:13:00,P,Schubuser,F,56,African American,General Practice,True,9.0,55,0,P Schubuser
3,358-31-9711,2024-02-04 22:34:00,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,0,U Titcombe
4,289-26-0537,2024-09-04 17:48:00,Y,Gionettitti,M,5,African American,Orthopedics,False,NaN,10,0,Y Gionettitti